## Import the Necessary Libraries

In [2]:
!pip install xgboost
!pip install lightgbm

Requirement already satisfied: xgboost in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (3.2.0)
Requirement already satisfied: numpy in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (2.2.6)
Requirement already satisfied: scipy in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (from xgboost) (1.15.3)

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

Collecting lightgbm
  Downloading lightgbm-4.7.0-py3-none-win_amd64.whl (1.4 MB)
     ---------------------------------------- 0.0/1.4 MB ? eta -:--:--
     -------------- ------------------------- 0.5/1.4 MB 15.9 MB/s eta 0:00:01
     ---------------------------------------  1.4/1.4 MB 17.2 MB/s eta 0:00:01
     ---------------------------------------- 1.4/1.4 MB 9.6 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.3 in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (2.2.6)
Requirement already satisfied: narwhals>=1.15 in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (2.26.0)
Requirement already satisfied: scipy in c:\users\madhumitha b\appdata\local\programs\python\python310\lib\site-packages (from lightgbm) (1.15.3)
Installing collected packages: lightgbm
Successfully installed lightgbm-4.7.0

[notice] A new release of pip is available: 23.0.1 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [5]:
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.ensemble import AdaBoostClassifier,GradientBoostingClassifier
from sklearn.metrics import confusion_matrix,accuracy_score,precision_score,recall_score

## Data Collection and Understanding

In [22]:
credit_data = pd.read_csv("credit_card_clean.csv")
credit_data

          ID  LIMIT_BAL     SEX   EDUCATION MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0          1    20000.0  female  university  married   24  ...     689.0       0.0       0.0       0.0       0.0        1
1          2   120000.0  female  university   single   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2          3    90000.0  female  university   single   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3          4    50000.0  female  university  married   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4          5    50000.0    male  university  married   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0
...      ...        ...     ...         ...      ...  ...  ...       ...       ...       ...       ...       ...      ...
29995  29996   220000.0    male  highschool  married   39  ...   20000.0    5003.0    3047.0    5000.0    1000.0        0
29996  29997   150000.0    male  highschool   single   43  ...    3526.0    8998.0     129.0       0.0       0.0        0
29997  29998    30000.0    male  university   single   37  ...       0.0   22000.0    4200.0    2000.0    3100.0        1
29998  29999    80000.0    male  highschool  married   41  ...    3409.0    1178.0    1926.0   52964.0    1804.0        1
29999  30000    50000.0    male  university  married   46  ...    1800.0    1430.0    1000.0    1000.0    1000.0        1

[30000 rows x 25 columns]

In [12]:
credit_data.shape

(30000, 25)

In [13]:
credit_data.isnull().sum()

ID           0
LIMIT_BAL    0
SEX          0
EDUCATION    0
MARRIAGE     0
AGE          0
PAY_1        0
PAY_2        0
PAY_3        0
PAY_4        0
PAY_5        0
PAY_6        0
BILL_AMT1    0
BILL_AMT2    0
BILL_AMT3    0
BILL_AMT4    0
BILL_AMT5    0
BILL_AMT6    0
PAY_AMT1     0
PAY_AMT2     0
PAY_AMT3     0
PAY_AMT4     0
PAY_AMT5     0
PAY_AMT6     0
DEFAULT      0
dtype: int64

In [14]:
credit_data.dtypes

ID             int64
LIMIT_BAL    float64
SEX           object
EDUCATION     object
MARRIAGE      object
AGE            int64
PAY_1          int64
PAY_2          int64
PAY_3          int64
PAY_4          int64
PAY_5          int64
PAY_6          int64
BILL_AMT1    float64
BILL_AMT2    float64
BILL_AMT3    float64
BILL_AMT4    float64
BILL_AMT5    float64
BILL_AMT6    float64
PAY_AMT1     float64
PAY_AMT2     float64
PAY_AMT3     float64
PAY_AMT4     float64
PAY_AMT5     float64
PAY_AMT6     float64
DEFAULT        int64
dtype: object

## Data Preparation

In [23]:
### Convert the columns sex, education, marriage into numbers by preprocessing (encoding technique) for the ML model to understand

le = LabelEncoder()

credit_data["SEX"] =  le.fit_transform(credit_data["SEX"])
credit_data["EDUCATION"] =  le.fit_transform(credit_data["EDUCATION"])
credit_data["MARRIAGE"] =  le.fit_transform(credit_data["MARRIAGE"])

In [24]:
credit_data

          ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  DEFAULT
0          1    20000.0    0          3         0   24  ...     689.0       0.0       0.0       0.0       0.0        1
1          2   120000.0    0          3         2   26  ...    1000.0    1000.0    1000.0       0.0    2000.0        1
2          3    90000.0    0          3         2   34  ...    1500.0    1000.0    1000.0    1000.0    5000.0        0
3          4    50000.0    0          3         0   37  ...    2019.0    1200.0    1100.0    1069.0    1000.0        0
4          5    50000.0    1          3         0   57  ...   36681.0   10000.0    9000.0     689.0     679.0        0
...      ...        ...  ...        ...       ...  ...  ...       ...       ...       ...       ...       ...      ...
29995  29996   220000.0    1          1         0   39  ...   20000.0    5003.0    3047.0    5000.0    1000.0        0
29996  29997   150000.0    1          1         2   43  ...    3526.0    8998.0     129.0       0.0       0.0        0
29997  29998    30000.0    1          3         2   37  ...       0.0   22000.0    4200.0    2000.0    3100.0        1
29998  29999    80000.0    1          1         0   41  ...    3409.0    1178.0    1926.0   52964.0    1804.0        1
29999  30000    50000.0    1          3         0   46  ...    1800.0    1430.0    1000.0    1000.0    1000.0        1

[30000 rows x 25 columns]

In [25]:
## Split X and y

## DEFAULT is the output column here in this dataset

X = credit_data.drop("DEFAULT", axis = 1)
y = credit_data["DEFAULT"]

In [26]:
X

          ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  ...  PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6
0          1    20000.0    0          3         0   24  ...       0.0     689.0       0.0       0.0       0.0       0.0
1          2   120000.0    0          3         2   26  ...       0.0    1000.0    1000.0    1000.0       0.0    2000.0
2          3    90000.0    0          3         2   34  ...    1518.0    1500.0    1000.0    1000.0    1000.0    5000.0
3          4    50000.0    0          3         0   37  ...    2000.0    2019.0    1200.0    1100.0    1069.0    1000.0
4          5    50000.0    1          3         0   57  ...    2000.0   36681.0   10000.0    9000.0     689.0     679.0
...      ...        ...  ...        ...       ...  ...  ...       ...       ...       ...       ...       ...       ...
29995  29996   220000.0    1          1         0   39  ...    8500.0   20000.0    5003.0    3047.0    5000.0    1000.0
29996  29997   150000.0    1          1         2   43  ...    1837.0    3526.0    8998.0     129.0       0.0       0.0
29997  29998    30000.0    1          3         2   37  ...       0.0       0.0   22000.0    4200.0    2000.0    3100.0
29998  29999    80000.0    1          1         0   41  ...   85900.0    3409.0    1178.0    1926.0   52964.0    1804.0
29999  30000    50000.0    1          3         0   46  ...    2078.0    1800.0    1430.0    1000.0    1000.0    1000.0

[30000 rows x 24 columns]

In [27]:
y

0        1
1        1
2        0
3        0
4        0
        ..
29995    0
29996    0
29997    1
29998    1
29999    1
Name: DEFAULT, Length: 30000, dtype: int64

In [28]:
## Split the dataset into training and testing data

X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,
    random_state=123,
    shuffle=True,
    stratify=y,)

In [30]:
print(X_train.shape,y_train.shape)
print(X_test.shape,y_test.shape)

(24000, 24) (24000,)
(6000, 24) (6000,)

## Model Building

In [46]:
adaboost =  AdaBoostClassifier()
gboost= GradientBoostingClassifier(n_estimators= 50,max_depth=3)
xgboost = XGBClassifier(n_estimators=50,max_depth=3)
lightgboost = LGBMClassifier(n_estimators=50,max_depth=3, force_col_wise= True)

In [41]:
%%time

adaboost_classifier =  adaboost.fit(X_train,y_train)

CPU times: total: 4.88 s
Wall time: 4.92 s

In [42]:
%%time

gb_classifier = gboost.fit(X_train,y_train)

CPU times: total: 12.7 s
Wall time: 12.9 s

In [48]:
%%time

xgb_classifier = xgboost.fit(X_train,y_train)

CPU times: total: 875 ms
Wall time: 175 ms

In [49]:
%%time

lightgb_classifier = lightgboost.fit(X_train,y_train)

[LightGBM] [Info] Number of positive: 5309, number of negative: 18691
[LightGBM] [Info] Total Bins 3514
[LightGBM] [Info] Number of data points in the train set: 24000, number of used features: 24
[LightGBM] [Info] [binary:BoostFromScore]: pavg=0.221208 -> initscore=-1.258639
[LightGBM] [Info] Start training from score -1.258639
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
CPU times: total: 1.05 s
Wall time: 180 ms

## Model Training and Model Evaluation

In [53]:
y_pred_ada = adaboost_classifier.predict(X_train)
y_pred_gb = gb_classifier.predict(X_train)
y_pred_xgb = xgb_classifier.predict(X_train)
y_pred_lightgb = lightgb_classifier.predict(X_train)

### AdaBoost Classifier

In [58]:
print("Confusion Matrix:", confusion_matrix(y_train,y_pred_ada))
print("Accuracy Score:", round(accuracy_score(y_train,y_pred_ada),4))
print("Precision Score:", round(precision_score(y_train,y_pred_ada),4))
print("Recall Score:", round(recall_score(y_train,y_pred_ada),4))

Confusion Matrix: [[17876   815]
 [ 3539  1770]]
Accuracy Score: 0.8186
Precision Score: 0.6847
Recall Score: 0.3334

### Gradient Boosting Classifier

In [61]:
print("Confusion Matrix:", confusion_matrix(y_train,y_pred_gb))
print("Accuracy Score:", round(accuracy_score(y_train,y_pred_gb),4))
print("Precision Score:", round(precision_score(y_train,y_pred_gb),4))
print("Recall Score:", round(recall_score(y_train,y_pred_gb),4))

Confusion Matrix: [[17833   858]
 [ 3353  1956]]
Accuracy Score: 0.8245
Precision Score: 0.6951
Recall Score: 0.3684

## Xtreme Gradient Boosting Classifier

In [64]:
print("Confusion Matrix:", confusion_matrix(y_train,y_pred_xgb))
print("Accuracy Score:", round(accuracy_score(y_train,y_pred_xgb),4))
print("Precision Score:", round(precision_score(y_train,y_pred_xgb),4))
print("Recall Score:", round(recall_score(y_train,y_pred_xgb),4))

Confusion Matrix: [[17825   866]
 [ 3293  2016]]
Accuracy Score: 0.8267
Precision Score: 0.6995
Recall Score: 0.3797

In [65]:
print("Confusion Matrix:", confusion_matrix(y_train,y_pred_lightgb))
print("Accuracy Score:", round(accuracy_score(y_train,y_pred_lightgb),4))
print("Precision Score:", round(precision_score(y_train,y_pred_lightgb),4))
print("Recall Score:", round(recall_score(y_train,y_pred_lightgb),4))

Confusion Matrix: [[17812   879]
 [ 3357  1952]]
Accuracy Score: 0.8235
Precision Score: 0.6895
Recall Score: 0.3677

## Model Testing and Model Evaluation

In [66]:
y_test_pred_ada = adaboost_classifier.predict(X_test)
y_test_pred_gb = gb_classifier.predict(X_test)
y_test_pred_xgb = xgb_classifier.predict(X_test)
y_test_pred_lightgb = lightgb_classifier.predict(X_test)

### Adaboost Classifier

In [68]:
print("Confusion Matrix:", confusion_matrix(y_test,y_test_pred_ada))
print("Accuracy Score:", round(accuracy_score(y_test,y_test_pred_ada),4))
print("Precision Score:", round(precision_score(y_test,y_test_pred_ada),4))
print("Recall Score:", round(recall_score(y_test,y_test_pred_ada),4))

Confusion Matrix: [[4487  186]
 [ 883  444]]
Accuracy Score: 0.8218
Precision Score: 0.7048
Recall Score: 0.3346

### Gradient Boosting Classifier

In [69]:
print("Confusion Matrix:", confusion_matrix(y_test,y_test_pred_gb))
print("Accuracy Score:", round(accuracy_score(y_test,y_test_pred_gb),4))
print("Precision Score:", round(precision_score(y_test,y_test_pred_gb),4))
print("Recall Score:", round(recall_score(y_test,y_test_pred_gb),4))

Confusion Matrix: [[4463  210]
 [ 850  477]]
Accuracy Score: 0.8233
Precision Score: 0.6943
Recall Score: 0.3595

### Xtreme Gradient Boosting Classifier

In [70]:
print("Confusion Matrix:", confusion_matrix(y_test,y_test_pred_xgb))
print("Accuracy Score:", round(accuracy_score(y_test,y_test_pred_xgb),4))
print("Precision Score:", round(precision_score(y_test,y_test_pred_xgb),4))
print("Recall Score:", round(recall_score(y_test,y_test_pred_xgb),4))

Confusion Matrix: [[4460  213]
 [ 844  483]]
Accuracy Score: 0.8238
Precision Score: 0.694
Recall Score: 0.364

### Light Gradient Boosting Classifier

In [71]:
print("Confusion Matrix:", confusion_matrix(y_test,y_test_pred_lightgb))
print("Accuracy Score:", round(accuracy_score(y_test,y_test_pred_lightgb),4))
print("Precision Score:", round(precision_score(y_test,y_test_pred_lightgb),4))
print("Recall Score:", round(recall_score(y_test,y_test_pred_lightgb),4))

Confusion Matrix: [[4462  211]
 [ 854  473]]
Accuracy Score: 0.8225
Precision Score: 0.6915
Recall Score: 0.3564